# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='_messages.proto',
  package='gateway',
  serialized_pb=_b('\n\x0f_messages.proto\x12\x07gateway\"\'\n\x13LoginRequestMessage\x12\x10\n\x08steam_id\x18\x01 \x01(\x03\"@\n\x14LoginResponseMessage\x12(\n\x0bstatus_code\x18\x01 \x02(\x0e\x32\x13.gateway.StatusCode*2\n\tMessageId\x12\x11\n\rLOGIN_REQUEST\x10\x01\x12\x12\n\x0eLOGIN_RESPONSE\x10\x02*\x19\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MESSAGEID = _descriptor.EnumDescriptor(
  name='MessageId',
  full_name='gateway.MessageId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOGIN_REQUEST', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_RESPONSE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=135,
  serialized_end=185,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEID)

MessageId = enum_type_wrapper.EnumTypeWrapper(_MESSAGEID)
_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='gateway.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=187,
  serialized_end=212,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
LOGIN_REQUEST = 1
LOGIN_RESPONSE = 2
SUCCESS = 0



_LOGINREQUESTMESSAGE = _descriptor.Descriptor(
  name='LoginRequestMessage',
  full_name='gateway.LoginRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steam_id', full_name='gateway.LoginRequestMessage.steam_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=67,
)


_LOGINRESPONSEMESSAGE = _descriptor.Descriptor(
  name='LoginResponseMessage',
  full_name='gateway.LoginResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='gateway.LoginResponseMessage.status_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=133,
)

_LOGINRESPONSEMESSAGE.fields_by_name['status_code'].enum_type = _STATUSCODE
DESCRIPTOR.message_types_by_name['LoginRequestMessage'] = _LOGINREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['LoginResponseMessage'] = _LOGINRESPONSEMESSAGE
DESCRIPTOR.enum_types_by_name['MessageId'] = _MESSAGEID
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE

LoginRequestMessage = _reflection.GeneratedProtocolMessageType('LoginRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUESTMESSAGE,
  __module__ = '_messages_pb2'
  # @@protoc_insertion_point(class_scope:gateway.LoginRequestMessage)
  ))
_sym_db.RegisterMessage(LoginRequestMessage)

LoginResponseMessage = _reflection.GeneratedProtocolMessageType('LoginResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSEMESSAGE,
  __module__ = '_messages_pb2'
  # @@protoc_insertion_point(class_scope:gateway.LoginResponseMessage)
  ))
_sym_db.RegisterMessage(LoginResponseMessage)


# @@protoc_insertion_point(module_scope)
